# Generated by Django 4.2.3 on 2023-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0003_alter_info_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(default='Correct city', max_length=50),
        ),
    ]
