# Generated by Django 4.2.3 on 2023-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0006_alter_info_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateField(default='2004-04-30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.TextField(default='clear'),
            preserve_default=False,
        ),
    ]
