# Generated by Django 4.2.3 on 2023-07-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0009_info_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='provide email', max_length=50),
            preserve_default=False,
        ),
    ]
