# Generated by Django 4.2.3 on 2023-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0010_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='dob',
            field=models.DateField(default='2004-04-30'),
            preserve_default=False,
        ),
    ]
